Refactor service

diff --git a/.github/workflows/manual_deployment.yaml b/.github/workflows/manual_deployment.yaml
--- a/.github/workflows/manual_deployment.yaml
+++ b/.github/workflows/manual_deployment.yaml
@@ -44,6 +44,12 @@ jobs:
           name: repository
           path: |
             ${{ github.workspace }}/deploy
+            ${{ github.workspace }}/docker
+            ${{ github.workspace }}/.dockerignore
+            ${{ github.workspace }}/main.go
+            ${{ github.workspace }}/main_test.go
+            ${{ github.workspace }}/go.mod
+            ${{ github.workspace }}/go.sum
 
   deploy:
     needs: [setup]
@@ -55,8 +61,8 @@ jobs:
           name: repository
       - name: Install kubectl
         run: |
-          curl -LO https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
-          curl -LO "https://dl.k8s.io/v1.22.0/bin/linux/amd64/kubectl.sha256"
+          curl -LO https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl
+          curl -LO "https://dl.k8s.io/v1.28.3/bin/linux/amd64/kubectl.sha256"
           echo "$(<kubectl.sha256) kubectl" | sha256sum --check
           sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
           kubectl version --client
@@ -64,18 +70,47 @@ jobs:
         run: |
           mkdir -p $HOME/.kube/
           case ${{ github.event.inputs.env }} in
-                qa) echo "${{ secrets.KUBE_QA_URL }}" > $HOME/.kube/config ;;
-            stage) echo "${{ secrets.KUBE_STAGE_URL }}" > $HOME/.kube/config ;;
-              prod) echo "${{ secrets.KUBE_PROD_URL }}" > $HOME/.kube/config ;;
+                qa) echo "${{ secrets.CLUSTER_QA_CONFIG }}" > $HOME/.kube/config ;;
+            stage) echo "${{ secrets.CLUSTER_STAGE_CONFIG }}" > $HOME/.kube/config ;;
+              prod) echo "${{ secrets.CLUSTER_PROD_CONFIG }}" > $HOME/.kube/config ;;
                 *) echo "Invalid environment"; exit 1;;
           esac
           case ${{ github.event.inputs.env }} in
-                qa) echo "${{ secrets.KUBE_QA_CONFIG }}" > $HOME/.kube/qa.yaml ;;
-            stage) echo "${{ secrets.KUBE_STAGE_CONFIG }}" > $HOME/.kube/stage.yaml ;;
-              prod) echo "${{ secrets.KUBE_PROD_CONFIG }}" > $HOME/.kube/prod.yaml ;;
+                qa) echo "${{ secrets.CLUSTER_QA_CLIENT_CERT }}" > $HOME/.kube/client.crt ;;
+            stage) echo "${{ secrets.CLUSTER_STAGE_CLIENT_CERT }}" > $HOME/.kube/client.crt ;;
+              prod) echo "${{ secrets.CLUSTER_PROD_CLIENT_CERT }}" > $HOME/.kube/client.crt ;;
+                *) echo "Invalid environment"; exit 1;;
+          esac
+          case ${{ github.event.inputs.env }} in
+                qa) echo "${{ secrets.CLUSTER_QA_CLIENT_KEY }}" > $HOME/.kube/client.key ;;
+            stage) echo "${{ secrets.CLUSTER_STAGE_CLIENT_KEY }}" > $HOME/.kube/client.key ;;
+              prod) echo "${{ secrets.CLUSTER_PROD_CLIENT_KEY }}" > $HOME/.kube/client.key ;;
+                *) echo "Invalid environment"; exit 1;;
+          esac
+          case ${{ github.event.inputs.env }} in
+                qa) echo "${{ secrets.CLUSTER_QA_ENV }}" > $HOME/.kube/qa.properties ;;
+            stage) echo "${{ secrets.CLUSTER_STAGE_ENV }}" > $HOME/.kube/stage.properties ;;
+              prod) echo "${{ secrets.CLUSTER_PROD_ENV }}" > $HOME/.kube/prod.properties ;;
+                *) echo "Invalid config"; exit 1;;
+          esac
+          case ${{ github.event.inputs.env }} in
+                qa) echo "${{ secrets.CLUSTER_QA_TLS_KEY }}" > $HOME/.kube/tls_ca.key ;;
+            stage) echo "${{ secrets.CLUSTER_STAGE_TLS_KEY }}" > $HOME/.kube/tls_ca.key ;;
+              prod) echo "${{ secrets.CLUSTER_PROD_TLS_KEY }}" > $HOME/.kube/tls_ca.key ;;
+                *) echo "Invalid config"; exit 1;;
+          esac
+          case ${{ github.event.inputs.env }} in
+                qa) echo "${{ secrets.CLUSTER_QA_TLS_CERT }}" > $HOME/.kube/tls_ca.crt ;;
+            stage) echo "${{ secrets.CLUSTER_STAGE_TLS_CERT  }}" > $HOME/.kube/tls_ca.crt ;;
+              prod) echo "${{ secrets.CLUSTER_PROD_TLS_CERT  }}" > $HOME/.kube/tls_ca.crt ;;
                 *) echo "Invalid config"; exit 1;;
           esac
       - name: Deploy
         run: |
           kubectl --kubeconfig $HOME/.kube/config delete secret -n ${{ github.event.inputs.env }} gf-config-secret
-          kubectl --kubeconfig $HOME/.kube/config create secret generic -n ${{ github.event.inputs.env }} gf-config-secret --from-env-file=$HOME/.kube/${{ github.event.inputs.env }}.yaml
+          kubectl --kubeconfig $HOME/.kube/config create secret generic -n ${{ github.event.inputs.env }} gf-config-secret --from-env-file=$HOME/.kube/${{ github.event.inputs.env }}.properties
+          kubectl --kubeconfig $HOME/.kube/config delete secret -n ${{ github.event.inputs.env }} tls-secret
+          kubectl --kubeconfig $HOME/.kube/config create secret tls -n ${{ github.event.inputs.env }} tls-secret --key $HOME/.kube/tls_ca.key --cert $HOME/.kube/tls_ca.crt
+          kubectl --kubeconfig $HOME/.kube/config delete secret -n ${{ github.event.inputs.env }} gf-config-cookie
+          kubectl --kubeconfig $HOME/.kube/config create secret generic -n ${{ github.event.inputs.env }} gf-config-cookie --from-literal=erlangCookie=$(dd if=/dev/urandom bs=30 count=1 | base64)
+          kubectl --kubeconfig $HOME/.kube/config apply -k deploy/k8s/${{ github.event.inputs.env }}
